Repository machinelearnjs/machinelearnjs, pull requests merged in 2018-12, with the labels that each got.

#149 Feature/tensor_ops -> reshape
  src/lib/ops/tensor_ops.ts
  test/ops/tensor_ops.test.ts
Labels: feature

#155 refactor/confusion matrix tfjs
  src/lib/metrics/classification.ts
Labels: enhancement

#154 refactor/PCA to tfjs
  CHANGELOG.md
  src/lib/decomposition/pca.ts
  src/lib/ops/index.repl.ts
  src/lib/ops/index.ts
  src/lib/ops/tensor_ops.ts
  test/decomposition/pca.test.ts
  test/ops/__snapshots__/tensor_ops.test.ts.snap
  test/ops/tensor_ops.test.ts
Labels: enhancement

#152 feature/v2_mean_absolute_error
  src/lib/metrics/index.repl.ts
  src/lib/metrics/index.ts
  src/lib/metrics/regression.ts
  test/integration/require.test.ts
  test/metrics/__snapshots__/regression.test.ts.snap
  test/metrics/regression.test.ts
Labels: feature

#142 refactor/naive bayes with tensors
  CHANGELOG.md
  docs/processor/index.ts
  src/lib/naive_bayes/gaussian.ts
  src/lib/naive_bayes/index.ts
  src/lib/naive_bayes/multinomial.ts
  src/lib/types/model.types.ts
  test/integration/require.test.ts
  test/naive_bayes/__snapshots__/gaussian.test.ts.snap
  test/naive_bayes/__snapshots__/multinomial.test.ts.snap
  test/naive_bayes/gaussian.test.ts
  test/naive_bayes/multinomial.test.ts
Labels: enhancement, feature
