Repository machinelearnjs/machinelearnjs, pull requests merged in 2018-10, with the labels that each got.

#82 :checkered_flag: Enabling building and testing under Windows
  Dockerfile
  package.json
  scripts/test-integration.js
  scripts/test-integration.sh
Labels: enhancement, hacktoberfest

#91 Feature/normalize l1 and l2
  src/lib/preprocessing/data.ts
  src/lib/utils/validation.ts
  test/preprocessing/data.test.ts
Labels: feature

#99 Feature: Husky pre-commit hook
  .travis.yml
  docs/processor/exampleConfig.ts
  package.json
  src/lib/linear_model/index.ts
  src/lib/preprocessing/data.ts
  src/lib/utils/validation.ts
  test/integration/require.test.ts
  test/preprocessing/data.test.ts
  yarn.lock
Labels: enhancement, feature

#124 Feature/v2 tensor ops
  package.json
  src/lib/ops/index.ts
  src/lib/ops/tensor_ops.ts
  src/lib/types/model_interfaces.ts
  test/ops/tensor_ops.test.ts
  yarn.lock
Labels: enhancement
